# Go dependencies
#
# Fetches all required Go dependencies. All Conduit sources are omitted from the resulting
# image so that artifacts may be built from source over this image.
#
# When this file is changed, run `bin/update-go-deps-shas`.

FROM golang:1.9.4
WORKDIR /go/src/github.com/runconduit/conduit

# Download `dep` without being sensitive to changes to Gopkg.{toml,lock}.
COPY bin/dep bin/dep
RUN bin/dep version

# Vendor the Go dependencies.
COPY Gopkg.toml Gopkg.lock ./
RUN bin/dep ensure -vendor-only -v

