# A base image for runtimes.
#
# This means that all Linkerd containers share a common set of tools, and furthermore, they
# are highly cacheable at runtime.

FROM debian:buster-20200514-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        curl \
        dnsutils \
        iptables \
        jq \
        nghttp2 \
    && rm -rf /var/lib/apt/lists/*

# Switching base image from stretch to buster, we need to use iptables-legacy
# if no changes to how iptables is invoked are done.
RUN update-alternatives --set iptables /usr/sbin/iptables-legacy \
    && update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
