ARG RUNTIME_IMAGE
FROM $RUNTIME_IMAGE
RUN apt-get update && apt-get install -y --no-install-recommends \
    tcpdump \
    iproute2 \
    lsof \
    tshark && \
    rm -rf /var/lib/apt/lists/*
ENTRYPOINT [ "tshark", "-i", "any" ]
