FROM gcr.io/linkerd-io/base:2019-09-17.01
RUN apt-get update && apt-get install -y --no-install-recommends \
    tcpdump \
    iproute2 \
    lsof \
    tshark && \
    rm -rf /var/lib/apt/lists/*
ENTRYPOINT [ "tshark", "-i", "any" ]
