ARG RUNTIME_IMAGE=gcr.io/linkerd-io/base:2017-10-30.01

FROM gcr.io/linkerd-io/base:2017-10-30.01 as fetch
RUN apt-get update && apt-get install -y ca-certificates
WORKDIR /build
COPY bin/fetch-proxy bin/fetch-proxy
ARG PROXY_VERSION
RUN (proxy=$(bin/fetch-proxy $PROXY_VERSION) && \
    version=$(basename "$proxy" | sed 's/linkerd2-proxy-//') && \
    mv "$proxy" linkerd2-proxy && \
    echo "$version" >version.txt)

FROM $RUNTIME_IMAGE as runtime
WORKDIR /linkerd
COPY --from=fetch /build/target/proxy/LICENSE ./LICENSE
COPY --from=fetch /build/linkerd2-proxy ./linkerd2-proxy
COPY --from=fetch /build/version.txt ./linkerd2-proxy-version.txt
ENV LINKERD2_PROXY_LOG=warn,linkerd2_proxy=info
ENTRYPOINT ["./linkerd2-proxy"]
