## compile binaries
FROM gcr.io/linkerd-io/go-deps:da6a119d as golang
WORKDIR /go/src/github.com/linkerd/linkerd2
COPY cli cli
COPY controller/k8s controller/k8s
COPY controller/api controller/api
COPY controller/gen controller/gen
COPY pkg pkg
RUN mkdir -p /out

# Install packr in order to use custom build command for static files
RUN CGO_ENABLED=0 go get -v github.com/gobuffalo/packr/v2/packr2

# Packr needs to build in the directory that the Box is relative to
WORKDIR /go/src/github.com/linkerd/linkerd2/cli

# Cache builds without version info
RUN CGO_ENABLED=0 GOOS=linux   packr2 build -o /out/linkerd-linux   -ldflags "-s -w"
RUN CGO_ENABLED=0 GOOS=windows packr2 build -o /out/linkerd-windows -ldflags "-s -w"
RUN CGO_ENABLED=0 GOOS=darwin  packr2 build -o /out/linkerd-darwin  -ldflags "-s -w"

ARG LINKERD_VERSION
ENV GO_LDFLAGS="-s -w -X github.com/linkerd/linkerd2/pkg/version.Version=${LINKERD_VERSION}"
RUN CGO_ENABLED=0 GOOS=darwin  packr2 build -o /out/linkerd-darwin  -ldflags "${GO_LDFLAGS}"
RUN CGO_ENABLED=0 GOOS=linux   packr2 build -o /out/linkerd-linux   -ldflags "${GO_LDFLAGS}"
RUN CGO_ENABLED=0 GOOS=windows packr2 build -o /out/linkerd-windows -ldflags "${GO_LDFLAGS}"

## export without sources & dependencies
WORKDIR /go/src/github.com/linkerd/linkerd2
FROM scratch
COPY LICENSE /linkerd/LICENSE
COPY --from=golang /out /out
# `ENTRYPOINT` prevents `docker build` from otherwise failing with "Error
# response from daemon: No command specified."
ENTRYPOINT ["/out/linkerd-linux"]
