{
 "title": "Linkerd Control Plane Metrics",
 "tags": [
  "linkerd-control-plane",
  "linkerd-mtls",
  "linkerd-injecton"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Request Rate to proxy Injector ",
   "type": "gauge",
   "description": "Checks the response request rate of the tproxies",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(proxy_inject_admission_responses_total{skip=\"false\"}[$__rate_interval])) by (component)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Certificate Refresh Rate by namespace",
   "type": "timeseries",
   "description": "How frequently the proxy is refreshing its mTLS identity certificate.",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(control_identity_cert_refreshes_total[$__rate_interval])) by ( workload_ns) ",
     "legendFormat": "ns/{{workload_ns}}"
    }
   ]
  },
  {
   "title": "Time Until Certificate Expiration",
   "type": "bargauge",
   "description": "Remaining lifetime of the mTLS certificate.",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((control_identity_cert_expiration_timestamp_seconds - time()) / 3600) by (namespace)",
     "legendFormat": "ns/{{namespace}}"
    }
   ]
  },
  { "title": "Linkerd Destination", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Success Rate to linkerd-dst",
   "type": "timeseries",
   "description": "Checks the response success rate of the target service and proxies",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(control_response_total{classification=\"success\",addr=~\"linkerd-dst-headless.linkerd.svc.*\"}[$__rate_interval])) by (addr)\n/\nsum(irate(control_response_total{addr=~\"linkerd-dst-headless.linkerd.svc.*\"}[$__rate_interval])) by (addr)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate to linkerd-dst",
   "type": "timeseries",
   "description": "Checks the response success rate of the target service and proxies",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(control_response_total{classification=\"failure\",addr=~\"linkerd-dst-headless.linkerd.svc.*\"}[$__rate_interval])) by (addr)\n/\nsum(irate(control_response_total{addr=~\"linkerd-dst-headless.linkerd.svc.*\"}[$__rate_interval])) by (addr)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate to linkerd-dst",
   "type": "timeseries",
   "description": "Checks the response request rate of the target service and proxies",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(irate(control_response_total{addr=~\"linkerd-dst-headless.linkerd.svc.*\"}[$__rate_interval])) by (addr)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency to linkerd-dst",
   "type": "timeseries",
   "description": "Checks the response latency  of the target service and proxies",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(control_response_latency_ms_bucket{addr=~\"linkerd-dst-headless.linkerd.svc.*\"}[$__rate_interval])) by (addr,le))",
     "legendFormat": "P50 - {{addr}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(control_response_latency_ms_bucket{addr=~\"linkerd-dst-headless.linkerd.svc.*\"}[$__rate_interval])) by (addr,le))",
     "legendFormat": "P95 - {{addr}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(control_response_latency_ms_bucket{addr=~\"linkerd-dst-headless.linkerd.svc.*\"}[$__rate_interval])) by (addr,le))",
     "legendFormat": "P99 - {{addr}}"
    }
   ]
  },
  { "title": "Linkerd Destination / Policy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Success Rate tol inkerd-policy",
   "type": "timeseries",
   "description": "Checks the response success rate of the target service and proxies",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(control_response_total{classification=\"success\",addr=~\"linkerd-policy.linkerd.svc.*\"}[$__rate_interval])) by (addr)\n/\nsum(irate(control_response_total{addr=~\"linkerd-policy.linkerd.svc.*\"}[$__rate_interval])) by (addr)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate tol inkerd-policy",
   "type": "timeseries",
   "description": "Checks the response error rate of the target service and proxies",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(control_response_total{classification=\"failure\",addr=~\"linkerd-policy.linkerd.svc.*\"}[$__rate_interval])) by (addr)\n/\nsum(irate(control_response_total{addr=~\"linkerd-policy.linkerd.svc.*\"}[$__rate_interval])) by (addr)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate to linkerd-policy",
   "type": "timeseries",
   "description": "Checks the response request rate of the target service and proxies",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(irate(control_response_total{addr=~\"linkerd-policy.linkerd.svc.*\"}[$__rate_interval])) by (addr)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency to linkerd-policy",
   "type": "timeseries",
   "description": "Checks the response latency  of the target service and proxies",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(control_response_latency_ms_bucket{addr=~\"linkerd-policy.linkerd.svc.*\"}[$__rate_interval])) by (addr,le))",
     "legendFormat": "P50 - {{addr}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(control_response_latency_ms_bucket{addr=~\"linkerd-policy.linkerd.svc.*\"}[$__rate_interval])) by (addr,le))",
     "legendFormat": "P95 - {{addr}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(control_response_latency_ms_bucket{addr=~\"linkerd-policy.linkerd.svc.*\"}[$__rate_interval])) by (addr,le))",
     "legendFormat": "P99 - {{addr}}"
    }
   ]
  },
  { "title": "Linkerd Identity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Success Rate to linkerd-identity-headless",
   "type": "timeseries",
   "description": "Checks the response success rate of the target service and proxies",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(control_response_total{classification=\"success\",addr=~\"linkerd-identity-headless.linkerd.svc.*\"}[$__rate_interval])) by (addr)\n/\nsum(irate(control_response_total{addr=~\"linkerd-identity-headless.linkerd.svc.*\"}[$__rate_interval])) by (addr)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate to linkerd-identity-headless",
   "type": "timeseries",
   "description": "Checks the response error rate of the target service and proxies",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(control_response_total{classification=\"failure\",addr=~\"linkerd-identity-headless.linkerd.svc.*\"}[$__rate_interval])) by (addr)\n/\nsum(irate(control_response_total{addr=~\"linkerd-identity-headless.linkerd.svc.*\"}[$__rate_interval])) by (addr)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate to linkerd-identity-headless",
   "type": "timeseries",
   "description": "Checks the response request rate of the target service and proxies",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(irate(control_response_total{addr=~\"linkerd-identity-headless.linkerd.svc.*\"}[$__rate_interval])) by (addr)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency to linkerd-identity-headless",
   "type": "timeseries",
   "description": "Checks the response latency  of the target service and proxies",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "\nhistogram_quantile(0.50, sum(rate(control_response_latency_ms_bucket{addr=~\"linkerd-identity-headless.linkerd.svc.*\"}[$__rate_interval])) by (addr,le))",
     "legendFormat": "P50 - {{addr}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(control_response_latency_ms_bucket{addr=~\"linkerd-identity-headless.linkerd.svc.*\"}[$__rate_interval])) by (addr,le))",
     "legendFormat": "P95 - {{addr}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(control_response_latency_ms_bucket{addr=\"linkerd-identity-headless.linkerd.svc.*\"}[$__rate_interval])) by (addr,le))",
     "legendFormat": "P99 - {{addr}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 29 },
   "options": {
    "content": "<div>\n  <div style=\"position: absolute; top: 0, left: 0\">\n    <a href=\"https://linkerd.io\" target=\"_blank\"><img src=\"https://linkerd.io/images/identity/svg/linkerd_primary_color_white.svg\" style=\"height: 30px;\"></a>\n  </div>\n  <div id=\"version\" style=\"position: absolute; top: 0; right: 0; font-size: 15px\">\n  </div>\n</div>\n<div style=\"display:none\">\n<script type=\"text/javascript\">\nvar localReqURL =\n  window.location.href.substring(\n    0,\n    window.location.href.indexOf(\n    \"/grafana/\"\n    )\n  )+'/overview';\n\nfetch(localReqURL, {\n  credentials: 'include',\n  headers: {\n    \"Content-Type\": \"text/html; charset=utf-8\",\n  },\n})\n.then(response => response.text())\n.then(text => (new window.DOMParser()).parseFromString(text, \"text/html\"))\n.then(html => {\n  var main = html.getElementById('main');\n  var localVersion = main.getAttribute(\"data-release-version\");\n  var versionElem = document.getElementById('version');\n\n  var channel;\n  var parts = localVersion.split(\"-\", 2);\n  if (parts.length === 2) {\n    channel = parts[0];\n    versionElem.innerHTML += 'Running Linkerd ' + parts[1] + ' (' + parts[0] + ')' + '.<br>';\n  } else {\n    versionElem.innerHTML += 'Running Linkerd ' + localVersion + '.<br>';\n  }\n  var uuid = main.getAttribute(\"data-uuid\");\n\n  fetch('https://versioncheck.linkerd.io/version.json?version='+localVersion+'&uuid='+uuid+'&source=grafana', {\n    credentials: 'include',\n    headers: {\n      \"Content-Type\": \"application/json; charset=utf-8\",\n    },\n  })\n  .then(response => response.json())\n  .then(json => {\n    if (!channel || !json[channel]) {\n      versionElem.innerHTML += 'Version check failed.'\n    } else if (json[channel] === localVersion) {\n      versionElem.innerHTML += 'Linkerd is up to date.';\n    } else {\n      parts = json[channel].split(\"-\", 2);\n      if (parts.length === 2) {\n        versionElem.innerHTML += \"A new \"+parts[0]+\" version (\"+parts[1]+\") is available.\"\n      } else {\n        versionElem.innerHTML += \"A new version (\"+json[channel]+\") is available.\"\n      }\n      versionElem.innerHTML += \" <a href='https://versioncheck.linkerd.io/update' target='_blank'>Update now</a>.\";\n    }\n  });\n});\n</script>\n</div>"
   }
  }
 ]
}