{
 "title": "Grafana metrics",
 "description": "Metrics about Grafana",
 "tags": [
  "grafana",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active instances",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{job=\"grafana\"}"
    }
   ]
  },
  {
   "title": "Dashboard count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "grafana_stat_totals_dashboard" }
   ]
  },
  {
   "title": "User count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "grafana_stat_total_users" }
   ]
  },
  {
   "title": "Playlist count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "grafana_stat_total_playlists" }
   ]
  },
  {
   "title": "Grafana version",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "targets": [
    { "expr": "topk(1, grafana_info)", "legendFormat": "{{version}}" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "content": "<br />\n<br />\n<center>\n<img src=\"public/img/grafana_icon.svg\"  style=\"height: 60px;\">\n<span style=\"color: red;font-size:3rem;line-height: 2rem;\">💖</span>\n<img src=\"public/app/plugins/datasource/prometheus/img/prometheus_logo.svg\" alt=\"Prometheus logo\" style=\"height: 60px;\">\n</center>"
  },
  {
   "title": "http status codes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (statuscode) (irate(http_request_total{job='grafana'}[5m]))",
     "legendFormat": "{{statuscode}}",
     "target": "dev.grafana.cb-office.alerting.active_alerts"
    }
   ]
  },
  {
   "title": "Requests by routing group",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(grafana_api_response_status_total[5m]))",
     "legendFormat": "api"
    },
    {
     "expr": "sum(irate(grafana_proxy_response_status_total[5m]))",
     "legendFormat": "proxy"
    },
    {
     "expr": "sum(irate(grafana_page_response_status_total[5m]))",
     "legendFormat": "web"
    }
   ]
  },
  {
   "title": "Most used handlers",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 5 },
   "targets": [
    {
     "expr": "sort(topk(8, sum by (handler) (http_request_total{job=\"grafana\"})))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Grafana alert results",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(grafana_alerting_result_total[1m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Prometheus alerts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": " sum (ALERTS)", "legendFormat": "firing alerts" }
   ]
  },
  {
   "title": "Grafana performance",
   "type": "graph",
   "description": "Aggregated over all Grafana nodes.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"grafana\"})",
     "legendFormat": "go routines",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=\"grafana\"})",
     "legendFormat": "memory usage"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 27 },
   "content": "<div>\n  <div style=\"position: absolute; top: 0, left: 0\">\n    <a href=\"https://linkerd.io\" target=\"_blank\"><img src=\"https://linkerd.io/images/identity/svg/linkerd_primary_color_white.svg\" style=\"height: 30px;\"></a>\n  </div>\n  <div id=\"version\" style=\"position: absolute; top: 0; right: 0; font-size: 15px\">\n  </div>\n</div>\n<script type=\"text/javascript\">\nvar localReqURL =\n  window.location.href.substring(\n    0,\n    window.location.href.indexOf(\n    \"/services/grafana:http/proxy/\"\n    )\n  )+'/services/web:http/proxy/overview';\n\nfetch(localReqURL, {\n  credentials: 'include',\n  headers: {\n    \"Content-Type\": \"text/html; charset=utf-8\",\n  },\n})\n.then(response => response.text())\n.then(text => (new window.DOMParser()).parseFromString(text, \"text/html\"))\n.then(html => {\n  var main = html.getElementById('main');\n  var localVersion = main.getAttribute(\"data-release-version\");\n  var channel;\n  var numericVersion = localVersion;\n  var parts = localVersion.split(\"-\", 2);\n  if (parts.length === 2) {\n    channel = parts[0];\n    numericVersion = parts[1];\n  }\n  var uuid = main.getAttribute(\"data-uuid\");\n\n  var versionElem = document.getElementById('version');\n  versionElem.innerHTML += 'Running Linkerd ' + numericVersion + '.<br>';\n\n  fetch('https://versioncheck.linkerd.io/version.json?version='+localVersion+'&uuid='+uuid+'&source=grafana', {\n    credentials: 'include',\n    headers: {\n      \"Content-Type\": \"application/json; charset=utf-8\",\n    },\n  })\n  .then(response => response.json())\n  .then(json => {\n    if (!json[channel]) {\n      versionElem.innerHTML += 'Version check failed.'\n    } else if (json[channel] === localVersion) {\n      versionElem.innerHTML += 'Linkerd is up to date.';\n    } else {\n      var parts = json[channel].split(\"-\", 2);\n      if (parts.length === 2) {\n        versionElem.innerHTML += \"A new \"+parts[0]+\" version (\"+parts[1]+\") is available.\"\n      } else {\n        versionElem.innerHTML += \"A new version (\"+json[channel]+\") is available.\"\n      }\n      versionElem.innerHTML += \" <a href='https://versioncheck.linkerd.io/update' target='_blank'>Update now</a>.\";\n    }\n  });\n});\n</script>"
  }
 ]
}