{
 "title": "Prometheus Benchmark - 2.0.x",
 "description": "Metrics useful for benchmarking and loadtesting Prometheus itself. Designed primarily for Prometheus 2.0.x",
 "tags": [ "prometheus" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Prometheus",
    "query": "query_result(up{job=\"prometheus\"} == 1)"
   }
  ]
 },
 "panels": [
  {
   "title": "Head Time series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=\"prometheus\",instance=\"$Prometheus:9090\"}",
     "legendFormat": "Time series"
    }
   ]
  },
  {
   "title": "Head Active Appenders",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_active_appenders{job=\"prometheus\",instance=\"$Prometheus:9090\"}"
    }
   ]
  },
  {
   "title": "Samples Appended/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=\"prometheus\",instance=\"$Prometheus:9090\"}[1m])",
     "legendFormat": "samples/s"
    }
   ]
  },
  {
   "title": "Head Chunks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{job=\"prometheus\",instance=\"$Prometheus:9090\"}",
     "legendFormat": "Chunks"
    }
   ]
  },
  {
   "title": "Head Chunks Created",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_chunks_created_total{job=\"prometheus\",instance=\"$Prometheus:9090\"}[1m])",
     "legendFormat": "Created"
    }
   ]
  },
  {
   "title": "Head Chunks Removed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_chunks_removed_total{job=\"prometheus\",instance=\"$Prometheus:9090\"}[1m])",
     "legendFormat": "Removed"
    }
   ]
  },
  {
   "title": "Head Time Range",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "dateTimeAsIso" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_min_time{job=\"prometheus\",instance=\"$Prometheus:9090\"}",
     "legendFormat": "Min"
    },
    { "expr": "time() * 1000", "legendFormat": "Now" },
    {
     "expr": "prometheus_tsdb_head_max_time{job=\"prometheus\",instance=\"$Prometheus:9090\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Head GC Time/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_gc_duration_seconds_sum{job=\"prometheus\",instance=\"$Prometheus:9090\"}[1m])"
    }
   ]
  },
  {
   "title": "Blocks Loaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_blocks_loaded{job=\"prometheus\",instance=\"$Prometheus:9090\"}"
    }
   ]
  },
  {
   "title": "TSDB Reloads/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_reloads_total{job=\"prometheus\",instance=\"$Prometheus:9090\"}[10m])",
     "legendFormat": "Reloads"
    },
    {
     "expr": "rate(prometheus_tsdb_reloads_failures_total{job=\"prometheus\",instance=\"$Prometheus:9090\"}[10m])",
     "legendFormat": "Failed Reloads"
    }
   ]
  },
  {
   "title": "WAL Fsync Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(tsdb_wal_fsync_duration_seconds_sum{job=\"prometheus\",instance=\"$Prometheus:9090\"}[1m]) / rate(tsdb_wal_fsync_duration_seconds_count{job=\"prometheus\",instance=\"$Prometheus:9090\"}[1m])"
    }
   ]
  },
  {
   "title": "WAL Corruptions/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(tsdb_wal_corruptions_total{job=\"prometheus\",instance=\"$Prometheus:9090\"}[10m])"
    }
   ]
  },
  {
   "title": "Compactions/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compactions_total{job=\"prometheus\",instance=\"$Prometheus:9090\"}[10m])",
     "legendFormat": "Compactions"
    },
    {
     "expr": "rate(prometheus_tsdb_compactions_failed_total{job=\"prometheus\",instance=\"$Prometheus:9090\"}[10m])",
     "legendFormat": "Failed Compactions"
    }
   ]
  },
  {
   "title": "Compactions Triggered/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compactions_triggered_total[10m])",
     "legendFormat": "Checkpoint duration"
    }
   ]
  },
  {
   "title": "Compaction Time/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_duration_sum{job=\"prometheus\",instance=\"$Prometheus:9090\"}[10m])"
    }
   ]
  },
  {
   "title": "First Compaction, Avg Chunk Time Range",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_chunk_range_sum{job=\"prometheus\",instance=\"$Prometheus:9090\"}[10m]) / rate(prometheus_tsdb_compaction_chunk_range_count{job=\"prometheus\",instance=\"$Prometheus:9090\"}[10m])"
    }
   ]
  },
  {
   "title": "First Compaction, Avg Chunk Samples",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_chunk_samples_sum{job=\"prometheus\",instance=\"$Prometheus:9090\"}[10m]) / rate(prometheus_tsdb_compaction_chunk_samples_count{job=\"prometheus\",instance=\"$Prometheus:9090\"}[10m])"
    }
   ]
  },
  {
   "title": "First Compaction, Avg Bytes/Sample",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_chunk_size_sum{job=\"prometheus\",instance=\"$Prometheus:9090\"}[10m]) / rate(prometheus_tsdb_compaction_chunk_samples_sum{job=\"prometheus\",instance=\"$Prometheus:9090\"}[10m])"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"prometheus\",instance=\"$Prometheus:9090\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "prometheus_local_storage_target_heap_size_bytes{job=\"prometheus\",instance=\"$Prometheus:9090\"}",
     "legendFormat": "Target heap size"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"prometheus\",instance=\"$Prometheus:9090\"}",
     "legendFormat": "Next GC"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"prometheus\",instance=\"$Prometheus:9090\"}",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"prometheus\",instance=\"$Prometheus:9090\"}[1m])",
     "legendFormat": "Allocated Bytes/s"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"prometheus\",instance=\"$Prometheus:9090\"}[1m])",
     "legendFormat": "Irate"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"prometheus\",instance=\"$Prometheus:9090\"}[5m])",
     "legendFormat": "5m rate"
    }
   ]
  },
  {
   "title": "Rule evaulation iterations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_evaluator_iterations_total{job=\"prometheus\",instance=\"$Prometheus:9090\"}[1m]) - rate(prometheus_evaluator_iterations_skipped_total{job=\"prometheus\",instance=\"$Prometheus:9090\"}[1m]) - rate(prometheus_evaluator_iterations_missed_total{job=\"prometheus\",instance=\"$Prometheus:9090\"}[1m])",
     "legendFormat": "Iterations performed/s"
    },
    {
     "expr": "rate(prometheus_evaluator_iterations_skipped_total{job=\"prometheus\",instance=\"$Prometheus:9090\"}[1m])  ",
     "legendFormat": "Iterations missed/s"
    },
    {
     "expr": "rate(prometheus_evaluator_iterations_missed_total{job=\"prometheus\",instance=\"$Prometheus:9090\"}[1m])",
     "legendFormat": "Iterations skipped/s"
    }
   ]
  },
  {
   "title": "Rule evaluation duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_evaluator_duration_seconds_sum{job=\"prometheus\",instance=\"$Prometheus:9090\"}[1m]) / rate(prometheus_evaluator_duration_seconds_count{job=\"prometheus\",instance=\"$Prometheus:9090\"}[1m])",
     "legendFormat": "Rule evaluation duration"
    }
   ]
  },
  {
   "title": "Query engine timings/s",
   "type": "graph",
   "description": "Time spent in each mode, per second",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_duration_seconds_sum{job=\"prometheus\",instance=\"$Prometheus:9090\"}[1m])",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "Disk Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_ms{job=\"node\",instance=\"$Prometheus:9100\"}[1m]) / 1000",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "512 * (irate(node_disk_sectors_read{job=\"node\",instance=\"$Prometheus:9100\"}[1m]) + irate(node_disk_sectors_written{job=\"node\",instance=\"$Prometheus:9100\"}[1m]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "(irate(node_disk_writes_completed{job=\"node\",instance=\"$Prometheus:9100\"}[1m]) + irate(node_disk_reads_completed{job=\"node\",instance=\"$Prometheus:9100\"}[1m]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 63 },
   "content": "<div>\n  <div style=\"position: absolute; top: 0, left: 0\">\n    <a href=\"https://linkerd.io\" target=\"_blank\"><img src=\"https://linkerd.io/images/identity/svg/linkerd_primary_color_white.svg\" style=\"height: 30px;\"></a>\n  </div>\n  <div id=\"version\" style=\"position: absolute; top: 0; right: 0; font-size: 15px\">\n  </div>\n</div>\n<script type=\"text/javascript\">\nvar localReqURL =\n  window.location.href.substring(\n    0,\n    window.location.href.indexOf(\n    \"/services/grafana:http/proxy/\"\n    )\n  )+'/services/web:http/proxy/overview';\n\nfetch(localReqURL, {\n  credentials: 'include',\n  headers: {\n    \"Content-Type\": \"text/html; charset=utf-8\",\n  },\n})\n.then(response => response.text())\n.then(text => (new window.DOMParser()).parseFromString(text, \"text/html\"))\n.then(html => {\n  var main = html.getElementById('main');\n  var localVersion = main.getAttribute(\"data-release-version\");\n  var uuid = main.getAttribute(\"data-uuid\");\n\n  var versionElem = document.getElementById('version');\n  versionElem.innerHTML += 'Running Linkerd ' + localVersion + '.<br>';\n\n  fetch('https://versioncheck.linkerd.io/version.json?version='+localVersion+'&uuid='+uuid+'&source=grafana', {\n    credentials: 'include',\n    headers: {\n      \"Content-Type\": \"application/json; charset=utf-8\",\n    },\n  })\n  .then(response => response.json())\n  .then(json => {\n    if (json.version === localVersion) {\n      versionElem.innerHTML += 'Linkerd is up to date.';\n    } else {\n      versionElem.innerHTML += \"A new version (\"+json.version+\") is available. <a href='https://versioncheck.linkerd.io/update' target='_blank'>Update now</a>.\";\n    }\n  });\n});\n</script>"
  }
 ]
}