{
 "title": "Conduit Replica Set",
 "tags": [ "conduit" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(request_total{conduit_io_control_plane_component=\"\"}, namespace)"
   },
   {
    "name": "replica_set",
    "label": "Replica Set",
    "query": "label_values(kube_pod_owner{namespace=\"$namespace\", owner_kind=\"ReplicaSet\"}, owner_name)"
   },
   {
    "name": "pod",
    "query": "label_values(kube_pod_owner{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=\"$replica_set\"}, pod)"
   },
   {
    "name": "inboundpod",
    "query": "label_values(request_total{dst_pod=~\"$pod\"}, pod)"
   },
   {
    "name": "outboundpod",
    "query": "label_values(request_total{pod=~\"$pod\"}, dst_pod)"
   },
   {
    "name": "inbound",
    "query": "label_values(kube_pod_owner{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", pod=~\"$inboundpod\"}, owner_name)"
   },
   {
    "name": "outbound",
    "query": "label_values(kube_pod_owner{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", pod=~\"$outboundpod\"}, owner_name)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2.4, "w": 24, "x": 0, "y": 0 },
   "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://conduit.io/favicon.png\" style=\"height:32px;\"/>&nbsp;\n  <span style=\"font-size: 32px\">rs/$replica_set</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 2.4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(response_total{direction=\"inbound\", classification=\"success\"}[30s]) * on(namespace, pod) group_left (owner_kind, owner_name) kube_pod_owner{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=\"$replica_set\"}) by (owner_name)\n/\nsum(irate(response_total{direction=\"inbound\"}[30s]) * on(namespace, pod) group_left (owner_kind, owner_name) kube_pod_owner{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=\"$replica_set\"}) by (owner_name)\n"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 2.4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(request_total{direction=\"inbound\"}[30s]) * on(namespace, pod) group_left (owner_kind, owner_name) kube_pod_owner{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=\"$replica_set\"}) by (owner_name)"
    }
   ]
  },
  {
   "title": "INBOUND REPLICA SETS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2.4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(kube_pod_owner{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=~\"$inbound\"}) by (owner_name))"
    }
   ]
  },
  {
   "title": "OUTBOUND REPLICA SETS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2.4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(kube_pod_owner{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=~\"$outbound\"}) by (owner_name))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 6.4 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>INBOUND TRAFFIC</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8.600000000000001 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{direction=\"inbound\", classification=\"success\"}[30s]) * on(namespace, pod) group_left (owner_kind, owner_name) kube_pod_owner{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=\"$replica_set\"}) by (owner_name)\n/\nsum(irate(response_total{direction=\"inbound\"}[30s]) * on(namespace, pod) group_left (owner_kind, owner_name) kube_pod_owner{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=\"$replica_set\"}) by (owner_name)\n",
     "legendFormat": "rs/{{owner_name}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8.600000000000001 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{direction=\"inbound\"}[30s]) * on(namespace, pod) group_left (owner_kind, owner_name) kube_pod_owner{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=\"$replica_set\"}) by (owner_name)",
     "legendFormat": "rs/{{owner_name}}"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8.600000000000001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(response_latency_ms_bucket{direction=\"inbound\"}[30s]) * on(namespace, pod) group_left (owner_kind, owner_name) kube_pod_owner{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=\"$replica_set\"}) by (le, owner_name))",
     "legendFormat": "p50 rs/{{owner_name}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{direction=\"inbound\"}[30s]) * on(namespace, pod) group_left (owner_kind, owner_name) kube_pod_owner{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=\"$replica_set\"}) by (le, owner_name))",
     "legendFormat": "p95 rs/{{owner_name}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{direction=\"inbound\"}[30s]) * on(namespace, pod) group_left (owner_kind, owner_name) kube_pod_owner{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=\"$replica_set\"}) by (le, owner_name))",
     "legendFormat": "p99 rs/{{owner_name}}"
    }
   ]
  },
  {
   "title": "Inbound TCP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15.600000000000001 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP CONNECTION FAILURES",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16.6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tcp_close_total{namespace=\"$namespace\", pod=~\"$pod\", direction=\"inbound\",classification=\"failure\"}",
       "legendFormat": "{{peer}} {{classification}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTIONS OPEN",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16.6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_open_connections{namespace=\"$namespace\", pod=~\"$pod\", direction=\"inbound\"}",
       "legendFormat": "{{peer}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTION DURATION",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16.6 },
     "targets": [
      {
       "expr": "tcp_connection_duration_ms_bucket{namespace=\"$namespace\", pod=~\"$pod\", direction=\"inbound\"}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16.6 } },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 17.6 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>INBOUND REPLICA SETS</span>\n</div>"
  },
  {
   "title": "rs/$inbound",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19.8 },
   "repeat": "inbound",
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20.8 },
     "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://conduit.io/favicon.png\" style=\"baseline; height:30px;\"/>&nbsp;\n  <span style=\"font-size: 15px; border-image:none\">rs/$inbound</span>\n</div>"
    },
    {
     "title": "SUCCESS RATE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22.8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(response_total{direction=\"outbound\", dst_pod=~\"$pod\", classification=\"success\"}[30s]) * on(namespace, pod) group_left (owner_kind, owner_name) kube_pod_owner{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=\"$inbound\"}) by (owner_name)\n/\nsum(irate(response_total{direction=\"outbound\", dst_pod=~\"$pod\"}[30s]) * on(namespace, pod) group_left (owner_kind, owner_name) kube_pod_owner{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=\"$inbound\"}) by (owner_name)",
       "legendFormat": "rs/{{owner_name}}"
      }
     ]
    },
    {
     "title": "REQUEST RATE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22.8 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(response_total{direction=\"outbound\", dst_pod=~\"$pod\"}[30s]) * on(namespace, pod) group_left (owner_kind, owner_name) kube_pod_owner{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=\"$inbound\"}) by (owner_name)",
       "legendFormat": "rs/{{owner_name}}"
      }
     ]
    },
    {
     "title": "LATENCY",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22.8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(response_latency_ms_bucket{direction=\"outbound\", dst_pod=~\"$pod\"}[30s]) * on(namespace, pod) group_left (owner_kind, owner_name) kube_pod_owner{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=\"$inbound\"}) by (le, owner_name))",
       "legendFormat": "P50 rs/{{owner_name}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{direction=\"outbound\", dst_pod=~\"$pod\"}[30s]) * on(namespace, pod) group_left (owner_kind, owner_name) kube_pod_owner{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=\"$inbound\"}) by (le, owner_name))",
       "legendFormat": "P95 rs/{{owner_name}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{direction=\"outbound\", dst_pod=~\"$pod\"}[30s]) * on(namespace, pod) group_left (owner_kind, owner_name) kube_pod_owner{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=\"$inbound\"}) by (le, owner_name))",
       "legendFormat": "P99 rs/{{owner_name}}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20.8 } },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 21.8 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>OUTBOUND TRAFFIC</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{direction=\"outbound\", pod=~\"$pod\", classification=\"success\"}[30s]) * on(namespace, dst_pod) group_left (owner_kind, owner_name) kube_pod_owner_ex{namespace=\"$namespace\", owner_kind=\"ReplicaSet\"}) by (owner_name)\n/\nsum(irate(response_total{direction=\"outbound\", pod=~\"$pod\"}[30s]) * on(namespace, dst_pod) group_left (owner_kind, owner_name) kube_pod_owner_ex{namespace=\"$namespace\", owner_kind=\"ReplicaSet\"}) by (owner_name)",
     "legendFormat": "rs/{{owner_name}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{direction=\"outbound\", pod=~\"$pod\"}[30s]) * on(namespace, dst_pod) group_left (owner_kind, owner_name) kube_pod_owner_ex{namespace=\"$namespace\", owner_kind=\"ReplicaSet\"}) by (owner_name)",
     "legendFormat": "rs/{{owner_name}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{direction=\"outbound\", pod=~\"$pod\"}[30s]) * on(namespace, dst_pod) group_left (owner_kind, owner_name) kube_pod_owner_ex{namespace=\"$namespace\", owner_kind=\"ReplicaSet\"}) by (le, owner_name))",
     "legendFormat": "P95 rs/{{owner_name}}"
    }
   ]
  },
  {
   "title": "Outbound TCP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP CONNECTION FAILURES",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tcp_close_total{namespace=\"$namespace\", pod=~\"$pod\", direction=\"outbound\",classification=\"failure\"}",
       "legendFormat": "{{peer}} {{classification}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTIONS OPEN",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_open_connections{namespace=\"$namespace\", pod=~\"$pod\", direction=\"outbound\"}",
       "legendFormat": "{{peer}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTION DURATION",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
     "targets": [
      {
       "expr": "tcp_connection_duration_ms_bucket{namespace=\"$namespace\", pod=~\"$pod\", direction=\"outbound\"}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "type": "text",
   "gridPos": { "h": 2.2, "w": 24, "x": 0, "y": 33 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>OUTBOUND REPLICA SETS</span>\n</div>"
  },
  {
   "title": "rs/$outbound",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35.2 },
   "repeat": "outbound",
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36.2 },
     "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://conduit.io/favicon.png\" style=\"baseline; height:30px;\"/>&nbsp;\n  <span style=\"font-size: 15px; border-image:none\">rs/$outbound</span>\n</div>"
    },
    {
     "title": "SUCCESS RATE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38.2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(response_total{direction=\"outbound\", pod=~\"$pod\", classification=\"success\"}[30s]) * on(namespace, dst_pod) group_left (owner_kind, owner_name) kube_pod_owner_ex{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=\"$outbound\"}) by (owner_name)\n/\nsum(irate(response_total{direction=\"outbound\", pod=~\"$pod\"}[30s]) * on(namespace, dst_pod) group_left (owner_kind, owner_name) kube_pod_owner_ex{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=\"$outbound\"}) by (owner_name)",
       "legendFormat": "rs/{{owner_name}}"
      }
     ]
    },
    {
     "title": "REQUEST RATE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38.2 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(request_total{direction=\"outbound\", pod=~\"$pod\"}[30s]) * on(namespace, dst_pod) group_left (owner_kind, owner_name) kube_pod_owner_ex{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=\"$outbound\"}) by (owner_name)",
       "legendFormat": "rs/{{owner_name}}"
      }
     ]
    },
    {
     "title": "LATENCY",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38.2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(response_latency_ms_bucket{direction=\"outbound\", pod=~\"$pod\"}[30s]) * on(namespace, dst_pod) group_left (owner_kind, owner_name) kube_pod_owner_ex{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=\"$outbound\"}) by (le, owner_name))",
       "legendFormat": "P50 rs/{{owner_name}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{direction=\"outbound\", pod=~\"$pod\"}[30s]) * on(namespace, dst_pod) group_left (owner_kind, owner_name) kube_pod_owner_ex{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=\"$outbound\"}) by (le, owner_name))",
       "legendFormat": "P95 rs/{{owner_name}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{direction=\"outbound\", pod=~\"$pod\"}[30s]) * on(namespace, dst_pod) group_left (owner_kind, owner_name) kube_pod_owner_ex{namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=\"$outbound\"}) by (le, owner_name))",
       "legendFormat": "P99 rs/{{owner_name}}"
      }
     ]
    }
   ]
  }
 ]
}