name: Actions

on:
  pull_request:
    paths:
      - .devcontainer/devcontainer.json
      - .github/workflows/**

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ${{ vars.LINKERD2_RUNNER || 'ubuntu-24.04' }}
    timeout-minutes: 10
    steps:
      - uses: linkerd/dev/actions/setup-tools@v50
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - run: just-dev lint-actions

  devcontainer-versions:
    runs-on: ${{ vars.LINKERD2_RUNNER || 'ubuntu-24.04' }}
    steps:
      - uses: linkerd/dev/actions/setup-tools@v50
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - run: just-dev check-action-images
