name: markdown

permissions:
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/markdown.yml
      - "**/*.md"

jobs:
  markdownlint:
    timeout-minutes: 5
    runs-on: ${{ vars.LINKERD2_RUNNER || 'ubuntu-24.04' }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd
        with:
          globs: |
            **/*.md
            !**/node_modules/**
            !target/**
