name: markdown

permissions:
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/markdown.yml
      - "**/*.md"

jobs:
  markdownlint:
    timeout-minutes: 5
    runs-on: ${{ vars.LINKERD2_RUNNER || 'ubuntu-24.04' }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: DavidAnson/markdownlint-cli2-action@6b51ade7a9e4a75a7ad929842dd298a3804ebe8b
        with:
          globs: |
            **/*.md
            !**/node_modules/**
            !target/**
